apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-router-envoy
  namespace: default
  labels:
    app: model-router-envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-router-envoy
  template:
    metadata:
      labels:
        app: model-router-envoy
    spec:
      containers:
      - name: model-router
        image: ghcr.io/agentic-layer/model-router-envoy:main
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 10000
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "500m"
        envFrom:
        - secretRef:
            name: openai-api-key