apiVersion: v1
kind: Service
metadata:
  name: model-router-envoy
  namespace: default
spec:
  selector:
    app: model-router-envoy
  ports:
    - protocol: TCP
      port: 10000
      targetPort: http
  type: ClusterIP